### ISSUE TITLE
Question about long structural cycles

### ISSUE THREAD

**Issue by rustyconover** [LAMPSPUC/StateSpaceModels.jl#173]
Hi,

Thanks for the really cool module.

I have data that has long "seasonal" cycles, think of data being sampled each minute and each day shows cyclical changes.  It seems that the larger I make the `s` parameter of the `structural` model the longer and longer it takes to fit.  

For example, it can take a really long time for 1000 data-points and 288 specified for s.  Is there some trick I can use to make things go faster?

Thanks,

Rusty

**Comment by guilhermebodin** [comment]
Hi @rustyconover, currently there is no trick that you can do to speed that up. But we are working on a branch `refactoring-to-0.4` that will give you some options that will be merged soon. Some of the options are:

- Model the seasonality as a cycle, this reduces the number of states.
- Implement a custom Kalman Filter for the structural model equation. 

As you grow the size of the system matrices, i.e. `T` the longer it takes to estimate because the Kalman Filter equations will cost more.

**Comment by rustyconover** [comment]
@guilhermebodin Thank you for your reply.  I understand now why having long cycles can be suboptimal.  Maybe I will downsample the data such that it results in data points.

Just in case you're interested, using your module has led me to the top of the real-time prediction leaderboard at [microprediction.org](https://microprediction.org).

**Comment by guilhermebodin** [comment]
@rustyconover I would love know more about the particular application. The refactoring-0.4 will handle real-time predictions in a much more efficient way.
